# Generated by Django 2.2.1 on 2019-05-08 20:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('10bb198e-ceb3-4271-9c71-f04964ecdb36'), primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('21903088-8d97-4a00-9499-992fc47b22c0'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('28e39d4d-2881-424f-996f-c50843b0fa57'), primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(choices=[('TO', 'to'), ('CC', 'cc'), ('BCC', 'bcc')], default='TO', max_length=3)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Person')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledMail',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('bf2056a4-6629-45bb-99cb-d4edded093a0'), primary_key=True, serialize=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Email')),
                ('recipients', models.ManyToManyField(to='app.Recipient')),
            ],
        ),
    ]
